/**
 * Seed 2-3 demo accounts (each with a distinct camera setup) for the Skip Login flow.
 *
 * Local dev (`npm run dev` with EVIDENCE_DEV_STORAGE=memory) auto-seeds this same
 * data on first request — no extra step needed there. This script instead:
 *  1. Verifies the seed data round-trips through the accountsDb accessors (mock D1).
 *  2. Prints the equivalent INSERT SQL so it can be applied to a real D1 database
 *     once provisioned, e.g.:
 *       npx tsx scripts/seed-accounts.ts > /tmp/seed-accounts.sql
 *       wrangler d1 execute <DB_NAME> --file=/tmp/seed-accounts.sql
 *
 * Run: npx tsx scripts/seed-accounts.ts
 */
import { insertAccount, insertCameraConfig, getMostRecentAccountWithCameraConfigs } from "../lib/accountsDb";
import { createDevAccountsBindings } from "../lib/devAccountsStore";
import { DEMO_ACCOUNTS_SEED } from "../lib/demoAccountsSeed";

function sqlString(value: string | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function printSeedSql() {
  console.log("-- Generated by scripts/seed-accounts.ts — apply with `wrangler d1 execute`");
  for (const seed of DEMO_ACCOUNTS_SEED) {
    const { id, name, createdAt, lastActiveAt } = seed.account;
    console.log(
      `INSERT INTO accounts (id, name, created_at, last_active_at) VALUES (${sqlString(id)}, ${sqlString(name)}, ${createdAt}, ${lastActiveAt});`,
    );
    for (const camera of seed.cameraConfigs) {
      console.log(
        `INSERT INTO camera_configs (id, account_id, camera_id, name, rtsp_url, remote_rtsp_url, connection_mode, username, password) VALUES (${sqlString(camera.id)}, ${sqlString(id)}, ${sqlString(camera.cameraId)}, ${sqlString(camera.name)}, ${sqlString(camera.rtspUrl)}, ${sqlString(camera.remoteRtspUrl)}, ${sqlString(camera.connectionMode ?? "local")}, ${sqlString(camera.username)}, ${sqlString(camera.password)});`,
      );
    }
  }
}

async function verifySeedRoundTrips() {
  const { db, reset } = createDevAccountsBindings();
  // createDevAccountsBindings auto-seeds; reset so we exercise insertAccount/insertCameraConfig directly.
  reset();

  for (const seed of DEMO_ACCOUNTS_SEED) {
    await insertAccount(db, seed.account);
    for (const camera of seed.cameraConfigs) {
      await insertCameraConfig(db, { ...camera, accountId: seed.account.id });
    }
  }

  const mostRecent = DEMO_ACCOUNTS_SEED.slice().sort(
    (a, b) => b.account.lastActiveAt - a.account.lastActiveAt,
  )[0];

  const resolved = await getMostRecentAccountWithCameraConfigs(db);
  if (!resolved || resolved.id !== mostRecent.account.id) {
    throw new Error("Most-recently-active account did not resolve as expected");
  }
  if (resolved.cameraConfigs.length !== mostRecent.cameraConfigs.length) {
    throw new Error("Camera config count mismatch for most-recently-active account");
  }
}

async function main() {
  await verifySeedRoundTrips();
  console.error(`seed-accounts: verified ${DEMO_ACCOUNTS_SEED.length} demo accounts round-trip OK`);
  printSeedSql();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
